name: CommandsExploder
description: "Now You can use && in Commands"
author: XanderID
version: 1.0.2
api: 4.0.0
main: XanderID\CommandsExploder\CommandsExploder

permissions:
 commandsexploder.use:
  default: op
  description: "Allow to Use CommandsExploder"
